services:
  web:
    build: .
    container_name: zabantu
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: zabantu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
