# Generated by Django 5.2.4 on 2025-08-23 14:27

import articles.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('analyse', 'Analyses'), ('article', 'Articles'), ('policy', 'Policy Briefs'), ('ouvrage', 'Ouvrages'), ('rapport', 'Rapports'), ('scholar', 'Publication Académique')], default='article', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sous-titre')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Contenu')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10, verbose_name='Statut')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=articles.models.article_upload_path, verbose_name='Fichier PDF')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='Image de couverture')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Éditeur')),
                ('journal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Revue')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('scholar_link', models.URLField(blank=True, null=True, verbose_name='Lien Scholar')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('is_academic', models.BooleanField(default=False, verbose_name='Publication académique')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Titre SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('publish_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'article sera automatiquement publié", null=True, verbose_name='Date de publication programmée')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guelekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('content', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='guelekan/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='guelekan/pdfs/%Y/%m/%d/')),
                ('guests', models.TextField(blank=True, help_text='Liste des invités/intervenants (un par ligne)', verbose_name='Invité(s)')),
                ('meta_title', models.CharField(blank=True, editable=False, max_length=60)),
                ('meta_description', models.CharField(blank=True, editable=False, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Date de publication programmée', null=True)),
            ],
            options={
                'verbose_name': 'Séminaire Guelekan',
                'verbose_name_plural': 'Séminaires Guelekan',
                'ordering': ['-created_at'],
            },
        ),
    ]
