# Generated by Django 5.2.4 on 2025-08-23 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteurs'),
        ),
        migrations.AddField(
            model_name='guelekan',
            name='galleries',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les galeries de photos à associer à ce séminaire', to='gallery.gallery', verbose_name='Galeries associées'),
        ),
    ]
