# Generated by Django 5.2.4 on 2025-08-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guelekan',
            name='guests',
            field=models.TextField(blank=True, help_text='Liste des invités/intervenants (un par ligne)', verbose_name='Invité(s)'),
        ),
    ]
