# Generated by Django 5.2.4 on 2025-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_meta_description_article_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='published', max_length=10),
        ),
    ]
