# Generated by Django 5.2.4 on 2025-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sous_titre',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('seminaire', 'Séminaire Gɛlɛkan'), ('analyse', 'Analyses'), ('article', 'Articles'), ('policy', 'Policy Briefs'), ('ouvrage', 'Ouvrages'), ('rapport', 'Rapports')], default='publication', max_length=20),
        ),
    ]
