# Generated by Django 5.2.4 on 2025-08-03 23:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_author_article_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guelekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sous_titre', models.CharField(blank=True, max_length=500)),
                ('content', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='guelekan/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='guelekan/files/')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('analyse', 'Analyses'), ('article', 'Articles'), ('policy', 'Policy Briefs'), ('ouvrage', 'Ouvrages'), ('rapport', 'Rapports')], default='publication', max_length=20),
        ),
    ]
