# Generated by Django 5.2.4 on 2025-08-04 18:21

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_guelekan_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sous_titre',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='guelekan',
            old_name='sous_titre',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish_at',
        ),
        migrations.RemoveField(
            model_name='guelekan',
            name='publish_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('analyse', 'Analyses'), ('article', 'Articles'), ('policy', 'Policy Briefs'), ('ouvrage', 'Ouvrages'), ('rapport', 'Rapports')], default='article', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='guelekan',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.guelekan_upload_path),
        ),
    ]
