# Generated by Django 5.2.4 on 2025-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_sous_titre_article_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Date de publication programmée', null=True),
        ),
        migrations.AddField(
            model_name='guelekan',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Date de publication programmée', null=True),
        ),
    ]
