# Generated by Django 5.2.4 on 2025-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_publish_at_guelekan_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_academic',
            field=models.BooleanField(default=False, verbose_name='Publication académique'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Éditeur'),
        ),
        migrations.AddField(
            model_name='article',
            name='scholar_link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Scholar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('analyse', 'Analyses'), ('article', 'Articles'), ('policy', 'Policy Briefs'), ('ouvrage', 'Ouvrages'), ('rapport', 'Rapports'), ('scholar', 'Publication Académique')], default='article', max_length=20),
        ),
    ]
