# Generated by Django 5.2.4 on 2025-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Mettre en avant cette galerie sur la page d'accueil", verbose_name='À la une')),
                ('cover_image', models.ImageField(blank=True, help_text='Image représentative de la galerie', null=True, upload_to='galleries/covers/', verbose_name='Image de couverture')),
            ],
            options={
                'verbose_name': 'Galerie',
                'verbose_name_plural': 'Galeries',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_all_galleries', 'Peut gérer toutes les galeries')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre descriptif de la photo', max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='galleries/photos/%Y/%m/%d/', verbose_name='Fichier image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_standalone', models.BooleanField(default=False, help_text="Cocher si cette photo n'appartient à aucune galerie", verbose_name='Photo indépendante')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-uploaded_at'],
                'permissions': [('can_manage_all_photos', 'Peut gérer toutes les photos')],
            },
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag photo',
                'verbose_name_plural': 'Tags photos',
                'ordering': ['name'],
            },
        ),
    ]
