# Generated by Django 5.2.4 on 2025-08-23 14:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('membre', 'Membre')], default='membre', max_length=20, verbose_name='rôle')),
                ('date_started', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format: '+999999999'. Jusqu'à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='téléphone')),
                ('profile_picture', models.ImageField(blank=True, default=None, upload_to='profiles/', verbose_name='photo de profil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biographie')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='poste')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='département')),
                ('social_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('social_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('social_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('social_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
