# Generated by Django 5.2.4 on 2025-08-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('membre', 'Membre')], default='moderateur', max_length=20),
        ),
    ]
