# Generated by Django 5.2.4 on 2025-08-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
