# Generated by Django 5.2.4 on 2025-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('event_type', models.CharField(choices=[('conference', 'Conférence'), ('formation', 'Formation'), ('seminaire', 'Séminaire'), ('autre', 'Autre')], default='seminaire', max_length=20, verbose_name="Type d'événement")),
                ('date', models.DateTimeField(verbose_name='Date et heure de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('lieu_gps', models.URLField(blank=True, max_length=550, null=True, verbose_name='Lien GPS')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('participant_type', models.CharField(choices=[('moderator', 'Modérateur'), ('speaker', 'Intervenant'), ('trainer', 'Formateur')], max_length=20, verbose_name='Type de participant')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/', verbose_name='Photo')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participant externe',
                'verbose_name_plural': 'Participants externes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
