# Generated by Django 5.2.4 on 2025-08-23 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_events', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='event',
            name='moderators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'participant_type': 'moderator'}, related_name='moderated_events', to='events.externalparticipant', verbose_name='Modérateurs'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'participant_type': 'speaker'}, related_name='speaker_events', to='events.externalparticipant', verbose_name='Intervenants'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'participant_type': 'trainer'}, related_name='training_events', to='events.externalparticipant', verbose_name='Formateurs'),
        ),
    ]
