# Generated by Django 5.2.4 on 2025-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lieu_gps',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
