# Generated by Django 5.2.4 on 2025-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_lieu_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lieu_gps',
            field=models.URLField(max_length=550),
        ),
    ]
