# Generated by Django 5.2.4 on 2025-08-06 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_lieu_gps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('participant_type', models.CharField(choices=[('moderator', 'Modérateur'), ('speaker', 'Intervenant'), ('trainer', 'Formateur')], max_length=20, verbose_name='Type de participant')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/', verbose_name='Photo')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Participant externe',
                'verbose_name_plural': 'Participants externes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conférence'), ('formation', 'Formation'), ('seminaire', 'Séminaire'), ('autre', 'Autre')], default='conference', max_length=20, verbose_name="Type d'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_events', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Date et heure de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lieu_gps',
            field=models.URLField(blank=True, max_length=550, null=True, verbose_name='Lien GPS'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='event',
            name='moderators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'participant_type': 'moderator'}, related_name='moderated_events', to='events.externalparticipant', verbose_name='Modérateurs'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'participant_type': 'speaker'}, related_name='speaker_events', to='events.externalparticipant', verbose_name='Intervenants'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'participant_type': 'trainer'}, related_name='training_events', to='events.externalparticipant', verbose_name='Formateurs'),
        ),
    ]
