# Generated by Django 5.2.4 on 2025-08-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_externalparticipant_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conférence'), ('formation', 'Formation'), ('seminaire', 'Séminaire'), ('autre', 'Autre')], default='seminaire', max_length=20, verbose_name="Type d'événement"),
        ),
    ]
